# Generated by Django 5.0.6 on 2024-06-04 23:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0006_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_email', message='The email must contain at least one lowercase letter, one number, and must be a @gmail.com or @yahoo.com address.', regex='^(?=.*[a-z])(?=.*[0-9])[a-zA-Z0-9._%+-]+@(gmail\\.com|yahoo\\.com $')]),
        ),
    ]
