# Generated by Django 5.0.6 on 2024-06-05 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0008_remove_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
