# Generated by Django 5.0.6 on 2024-06-05 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0009_customuser_first_name_customuser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
