# Generated by Django 5.0.6 on 2024-06-05 01:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0011_alter_customuser_options_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Password must be at least 8 characters long, contain at least one uppercase letter, one lowercase letter, and one digit.', regex='^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d).{8,}$')]),
        ),
    ]
