# Generated by Django 5.0.6 on 2024-06-05 01:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0012_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(message='Password must contain at least 8 characters, one uppercase letter, one lowercase letter, and one number', regex='^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d).{8,}$')]),
        ),
    ]
