# Generated by Django 5.0.6 on 2024-06-05 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0014_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
