# Generated by Django 5.0.6 on 2024-06-07 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0016_todo_user_alter_customuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
    ]
