# Generated by Django 5.0.6 on 2024-06-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0020_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics/'),
        ),
    ]
