# Generated by Django 5.0.6 on 2024-06-25 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0022_todo_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='blog_image',
        ),
    ]
