# Generated by Django 5.0.6 on 2024-06-26 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0026_customuser_bio_customuser_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
    ]
