# Generated by Django 5.0.6 on 2024-06-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0029_customuser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='blog_image',
            field=models.ImageField(blank=True, null=True, upload_to='todo_images/'),
        ),
    ]
