# Generated by Django 5.0.7 on 2024-08-03 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0030_alter_todo_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='forgot_password_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
